# Generated by Django 3.2.5 on 2021-08-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_activation_peppolid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='peppolID',
            field=models.CharField(blank=True, default='', max_length=20, unique=True),
        ),
    ]
