# Generated by Django 3.2.5 on 2021-08-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_messages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='xml_type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
