# Generated by Django 3.2.5 on 2021-08-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_messages', '0003_rename_invoice_message_xml'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='peppol_classic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='peppol_direct',
            field=models.BooleanField(default=False),
        ),
    ]
