# Generated by Django 3.2.5 on 2021-08-20 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_messages', '0004_auto_20210820_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='peppol_direct',
        ),
    ]
