# Generated by Django 3.2.3 on 2021-07-04 14:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('connection', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FriendshipRequest',
            new_name='ConnectionRequest',
        ),
        migrations.RenameModel(
            old_name='Friend',
            new_name='Contact',
        ),
        migrations.AlterModelOptions(
            name='connectionrequest',
            options={'verbose_name': 'Connection Request', 'verbose_name_plural': 'Connection Requests'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
    ]
