# Generated by Django 3.2.5 on 2021-08-17 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0002_auto_20210812_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='is_customer',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='is_supplier',
        ),
    ]
