# Generated by Django 3.2.3 on 2021-06-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceform',
            name='Name',
        ),
        migrations.AddField(
            model_name='invoiceform',
            name='first_name',
            field=models.CharField(default='SOME STRING', max_length=140),
        ),
    ]
