# Generated by Django 3.2.3 on 2021-06-01 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_auto_20210601_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceform',
            name='email',
            field=models.EmailField(default='example@host.com', max_length=70),
        ),
        migrations.AddField(
            model_name='invoiceform',
            name='last_name',
            field=models.CharField(default='last name', max_length=50),
        ),
        migrations.AlterField(
            model_name='invoiceform',
            name='first_name',
            field=models.CharField(default='first name', max_length=140),
        ),
    ]
