# Generated by Django 3.2.3 on 2021-06-02 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_auto_20210601_1550'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InvoiceForm',
            new_name='Invoice',
        ),
    ]
