# Generated by Django 3.2.3 on 2021-06-02 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_rename_invoiceform_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='email',
        ),
        migrations.AddField(
            model_name='invoice',
            name='website',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='first_name',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
